In [ ]:
import pandas as pd
import numpy as np

In [ ]:
data=pd.read_csv("/content/Student_Performance.csv")
display(data)

,Hours Studied,Previous Scores,Extracurricular Activities,Sleep Hours,Sample Question Papers Practiced,Performance Index
0,7,99,Yes,9,1,91.0
1,4,82,No,4,2,65.0
2,8,51,Yes,7,2,45.0
3,5,52,Yes,5,2,36.0
4,7,75,No,8,5,66.0
...,...,...,...,...,...,...
9995,1,49,Yes,4,2,23.0
9996,7,64,Yes,8,5,58.0
9997,6,83,Yes,8,5,74.0
9998,9,97,Yes,7,0,95.0
9999,7,74,No,8,1,64.0

In [ ]:
print('shape',data.shape)
print("="*60)
print('index',data.index)
print("="*60)
print('info',data.info())
print("="*60)
print('colums',data.columns)
print("="*60)
print('describe',data.describe())

shape (10000, 6)
============================================================
index RangeIndex(start=0, stop=10000, step=1)
============================================================
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 6 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   Hours Studied                     10000 non-null  int64
 1   Previous Scores                   10000 non-null  int64
 2   Extracurricular Activities        10000 non-null  object
 3   Sleep Hours                       10000 non-null  int64
 4   Sample Question Papers Practiced  10000 non-null  int64
 5   Performance Index                 10000 non-null  float64
dtypes: float64(1), int64(4), object(1)
memory usage: 468.9+ KB
info None
============================================================
colums Index(['Hours Studied', 'Previous Scores', 'Extracurricular Activities',
       'Sleep Hours', 'Sample Question Papers Practiced', 'Performance Index'],
      dtype='object')
============================================================
describe        Hours Studied  Previous Scores   Sleep Hours  \
count   10000.000000     10000.000000  10000.000000
mean        4.992900        69.445700      6.530600
std         2.589309        17.343152      1.695863
min         1.000000        40.000000      4.000000
25%         3.000000        54.000000      5.000000
50%         5.000000        69.000000      7.000000
75%         7.000000        85.000000      8.000000
max         9.000000        99.000000      9.000000

       Sample Question Papers Practiced  Performance Index
count                      10000.000000       10000.000000
mean                           4.583300          55.224800
std                            2.867348          19.212558
min                            0.000000          10.000000
25%                            2.000000          40.000000
50%                            5.000000          55.000000
75%                            7.000000          71.000000
max                            9.000000         100.000000

In [ ]:
display(data.info())
display(data.describe())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 6 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   Hours Studied                     10000 non-null  int64
 1   Previous Scores                   10000 non-null  int64
 2   Extracurricular Activities        10000 non-null  object
 3   Sleep Hours                       10000 non-null  int64
 4   Sample Question Papers Practiced  10000 non-null  int64
 5   Performance Index                 10000 non-null  float64
dtypes: float64(1), int64(4), object(1)
memory usage: 468.9+ KB

None

,Hours Studied,Previous Scores,Sleep Hours,Sample Question Papers Practiced,Performance Index
count,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000
mean,4.992900,69.445700,6.530600,4.583300,55.224800
std,2.589309,17.343152,1.695863,2.867348,19.212558
min,1.000000,40.000000,4.000000,0.000000,10.000000
25%,3.000000,54.000000,5.000000,2.000000,40.000000
50%,5.000000,69.000000,7.000000,5.000000,55.000000
75%,7.000000,85.000000,8.000000,7.000000,71.000000
max,9.000000,99.000000,9.000000,9.000000,100.000000

In [ ]:
data['Previous Scores'].mean(),

np.float64(69.4457)

In [ ]:
data['Sleep Hours'].median()

7.0

In [ ]:
data['Hours Studied'].mode()[0]

np.int64(1)

In [ ]:
data['Sleep Hours'].min()

4

In [ ]:
data.columns

Index(['Hours Studied', 'Previous Scores', 'Extracurricular Activities',
       'Sleep Hours', 'Sample Question Papers Practiced', 'Performance Index'],
      dtype='object')

In [ ]:
a=['Hours Studied', 'Previous Scores','Sleep Hours', 'Extracurricular Activities','Sample Question Papers Practiced', 'Performance Index']

In [ ]:

for i in a:
  if i!='Extracurricular Activities':
    print(f"mean of {i} = {data[i].mean()}")

    print(f"median of {i}={data[i].median()}")

    print(f"mode of {i}={data [i].mode()[0]}")
    print("="*30)
  else:
    print(f"mode of {i}={data [i].mode()[0]}")

mean of Hours Studied = 4.9929
median of Hours Studied=5.0
mode of Hours Studied=1
==============================
mean of Previous Scores = 69.4457
median of Previous Scores=69.0
mode of Previous Scores=54
==============================
mean of Sleep Hours = 6.5306
median of Sleep Hours=7.0
mode of Sleep Hours=8
==============================
mode of Extracurricular Activities=No
mean of Sample Question Papers Practiced = 4.5833
median of Sample Question Papers Practiced=5.0
mode of Sample Question Papers Practiced=6
==============================
mean of Performance Index = 55.2248
median of Performance Index=55.0
mode of Performance Index=67.0
==============================

In [ ]:
b=['Hours Studied', 'Previous Scores','Sleep Hours','Sample Question Papers Practiced', 'Performance Index']

In [ ]:
for i in b:
  print(f'range of {i}={data[i].max()-data[i].min()}')
  print(f'std of {i}={data[i].std()}')
  print(f'variance of {i}={data[i].var()}')

  q1 = data[i].quantile(0.25)
  q3 = data[i].quantile(0.75)
  iqr = q3 - q1

  print(f'iqr of {i}={iqr}')
  print(f'skewness of {i}={data[i].skew()}')
  print(f' kurtosis of {i}={data[i].kurtosis()}')
  print("="*65)

range of Hours Studied=8
std of Hours Studied=2.589308796185612
variance of Hours Studied=6.704520042004183
iqr of Hours Studied=4.0
skewness of Hours Studied=-0.004212515950724343
 kurtosis of Hours Studied=-1.2321440232552219
=================================================================
range of Previous Scores=59
std of Previous Scores=17.343152251047066
variance of Previous Scores=300.7849300029989
iqr of Previous Scores=31.0
skewness of Previous Scores=0.004501683134743138
 kurtosis of Previous Scores=-1.2132371256847054
=================================================================
range of Sleep Hours=5
std of Sleep Hours=1.6958629765176023
variance of Sleep Hours=2.875951235123142
iqr of Sleep Hours=3.0
skewness of Sleep Hours=-0.03947379005452839
 kurtosis of Sleep Hours=-1.2568875912943394
=================================================================
range of Sample Question Papers Practiced=9
std of Sample Question Papers Practiced=2.8673477777081713
variance of Sample Question Papers Practiced=8.221683278327989
iqr of Sample Question Papers Practiced=5.0
skewness of Sample Question Papers Practiced=-0.035635999762971604
 kurtosis of Sample Question Papers Practiced=-1.2145565191984562
=================================================================
range of Performance Index=90.0
std of Performance Index=19.212557799463323
variance of Performance Index=369.12237719771895
iqr of Performance Index=31.0
skewness of Performance Index=-0.0017400273072201125
 kurtosis of Performance Index=-0.8605230998210018
=================================================================